name: Debug Build (APK)

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Create Secrets file
        run: |
          echo "Creating debug secrets file from template"
          cp ./lib/constant/secrets.dart.template ./lib/constant/secrets.dart

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.35.2

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Install flutter_rust_bridge_codegen
        run: cargo install flutter_rust_bridge_codegen

      - name: Install cargo-expand
        run: cargo install cargo-expand

      - name: Get Packages
        run: flutter pub get

      - name: Generate Rust
        run: flutter_rust_bridge_codegen generate

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29-beta4

      - uses: SimonMarquis/android-accept-licenses@v1

      - name: Build Debug APKs
        run: flutter build apk --debug --split-per-abi

      - name: Upload Debug Build to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            build/app/outputs/flutter-apk/app-arm64-v8a-debug.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-debug.apk
            build/app/outputs/flutter-apk/app-x86_64-debug.apk


